// Smoke test: localStorage mode, walks the diagnosis + issues features, an engine sale with a swap,
// an ECM job from intake to invoice (including the emissions block), the sales research
// (prospect seeds, a logged visit with a follow-up, convert to customer, route sheet), the
// 3D shop (engines placed by status, give one a spot, reload, the Engines list shows it), and
// timesheets: an employee's screen and the owner's approval in localStorage mode, then the cloud
// build against a mock Supabase (a real Postgres with the repo's migrations) where the owner gives
// an employee a login and the database rules are checked through the app and straight at the API.
import { chromium } from "playwright";
import { spawn, execSync } from "child_process";
import { createServer } from "http";
import { mockSupabase } from "./tests/fixtures/mock-supabase.mjs";
import { loadEdgeFunction } from "./tests/fixtures/edge.mjs";
const srv=spawn("npx",["vite","preview","--port","4173","--strictPort"],{stdio:"ignore"});
await new Promise(r=>setTimeout(r,2500));
const errs=[];
// SwiftShader gives headless Chromium WebGL, which the Shop 3D view needs.
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium",args:["--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"]}).catch(()=>chromium.launch());
const p=await b.newPage({viewport:{width:1280,height:900}});
p.on("pageerror",e=>errs.push("pageerror: "+e.message));
// A failed load names its URL, so the expected ones (favicon, Google Fonts behind the proxy) are easy to tell apart.
const errOf=m=>m.text()+(/Failed to load resource/.test(m.text())&&m.location().url?" ("+m.location().url+")":"");
p.on("console",m=>{if(m.type()==="error")errs.push("console: "+errOf(m));});
await p.goto("http://localhost:4173/");
await p.waitForSelector(".rc-side");
// Issues tab
await p.click('.rc-ni:has-text("Issues")');
await p.waitForSelector("text=Common Issues");
await p.screenshot({path:"shot-issues.png",fullPage:false});
const rows=await p.locator("table.rc-tbl tbody tr").count();
console.log("issues rows:",rows);
// filter by model ISX15
await p.click("button.rc-fb:has-text('ISX15')");
const isx=await p.locator("table.rc-tbl tbody tr").count();
console.log("ISX15 rows:",isx);
// open engine passport for an ISX-15
await p.click('.rc-ni:has-text("Engines")');
await p.fill("input.rc-si","ISX-15 (2010)");
await p.click("table.rc-tbl tbody tr >> nth=0 >> td >> nth=1");
await p.waitForSelector("text=Engine Unit Record");
await p.click(".rc-mod button.rc-fb:has-text('Diagnosis')");
await p.waitForSelector("text=Diagnosis history");
const known=await p.locator("text=/known issues? for/").innerText();
console.log("passport:",known);
await p.screenshot({path:"shot-passport.png"});
// log a diagnosis
await p.click(".rc-mod button:has-text('+ Log Diagnosis')");
await p.waitForSelector("text=Log Diagnosis");
await p.click("button.rc-fb:has-text('Hard start')");
await p.click("button.rc-fb:has-text('Low power')");
await p.waitForSelector("text=matching known issue");
await p.fill("input[placeholder^='Fault codes']","SPN 157 FMI 18");
await p.fill("textarea[placeholder^='Findings']","Metal in fuel filter, rail pressure low vs commanded.");
await p.fill("textarea[placeholder^='Fix']","XPI pump + injectors, flushed rails.");
await p.fill("input[placeholder='Hours']","3");
await p.fill("input[placeholder='Rate ($/hr)']","120");
await p.click(".rc-mod button:has-text('+ Part')");
await p.fill("input[placeholder='Part']","XPI pump");
await p.fill("input[placeholder='$']","2400");
await p.screenshot({path:"shot-dxform.png"});
await p.click(".rc-fa button.rc-ba:has-text('Save')");
await p.waitForSelector("text=Engine Unit Record");
await p.click(".rc-mod button.rc-fb:has-text('Costs')");
const cb=await p.locator("text=Total in this engine").locator("xpath=..").innerText();
console.log("cost basis line:",cb.replace(/\s+/g," "));
const dxParts=await p.locator("text=Diagnosis parts").count();
console.log("diagnosis parts row present:",dxParts>0);
await p.screenshot({path:"shot-passport2.png"});
// open diagnosis detail → add to common issues
await p.click(".rc-mod button.rc-fb:has-text('Diagnosis')");
await p.click("text=Hard start, Low power");
await p.waitForSelector("text=Add to common issues");
await p.click(".rc-mod button:has-text('Add to common issues')");
await p.waitForSelector("text=Add Common Issue");
// the form is filled one render after it opens: wait for the value instead of reading the first frame
await p.waitForFunction(()=>{const el=document.querySelector("input[placeholder^='Title']");return el&&el.value;},null,{timeout:3000}).catch(()=>{});
const title=await p.inputValue("input[placeholder^='Title']");
const models=await p.inputValue("input[placeholder^='Engine models']");
console.log("prefill title:",title,"| models:",models);
await p.click(".rc-fa button.rc-ba:has-text('Save')");
await p.waitForSelector("text=Linked common issue");
await p.screenshot({path:"shot-dxdetail.png"});
await p.keyboard.press("Escape");
await p.click(".rc-ov",{position:{x:5,y:5}}).catch(()=>{});
await p.waitForTimeout(1500);
// reload → persisted?
await p.reload();
await p.waitForSelector(".rc-side");
await p.click('.rc-ni:has-text("Issues")');
await p.click("button.rc-fb:has-text('Diagnosis Log')");
const logRows=await p.locator("table.rc-tbl tbody tr").count();
console.log("diagnosis log rows after reload:",logRows);
await p.screenshot({path:"shot-log.png"});
const shopIssues=await p.locator("text=/1 from this shop/").count();
console.log("shop-sourced issue counted:",shopIssues>0);
await p.click("table.rc-tbl tbody tr >> nth=0 >> td >> nth=3");await p.waitForSelector("text=Diagnosis");console.log("linked issue survives reload:",await p.locator("text=Linked common issue").count()>0);
// Services: sell an engine with an engine swap → one invoice carrying the engine + the swap, a swap
// work order billed on it, and hours logged on the swap stay off the engine's cost basis.
await p.click(".rc-ov",{position:{x:5,y:5}}).catch(()=>{});
const LS=k=>p.evaluate(k=>JSON.parse(localStorage.getItem("rc:"+k)||"[]"),k);
await p.click('.rc-ni:has-text("Team")');
await p.click('button.rc-ba:has-text("+ Employee")');
await p.fill(".rc-mod input[placeholder='Name']","Dale");
await p.fill(".rc-mod input[placeholder='Rate ($/hr)']","40");
await p.click(".rc-mod .rc-fa .rc-ba");
await p.click('.rc-ni:has-text("Engines")');
await p.fill("input.rc-si","ISX-15 (2012)");
await p.click("table.rc-tbl tbody tr >> nth=0 >> td >> nth=1");
await p.waitForSelector("text=Engine Unit Record");
await p.click(".rc-mod .rc-fa button:has-text('Sell Engine')");
await p.waitForSelector("text=What's going with this engine?");
await p.fill(".rc-mod input[aria-label^='Charge for Engine swap — install']","6500");
await p.fill(".rc-mod input[placeholder^='Name — add phone']","Smoke Test Hauling");
await p.screenshot({path:"shot-sell.png"});
await p.click(".rc-mod .rc-fa .rc-ba");
await p.waitForSelector(".rc-splash",{timeout:5000}).then(()=>p.click(".rc-splash")).catch(()=>{});
await p.waitForTimeout(900);
const sInv=(await LS("invoices")).find(x=>(x.items||[]).some(l=>l.svcId===85101));
const sJob=(await LS("jobs")).find(j=>j.svcId===85101);
console.log("sold with a swap — invoice lines:",sInv?sInv.items.length:0,"| swap work order billed on it:",!!(sInv&&sJob&&sJob.invoiceId===sInv.id));
const lab0=+((await LS("inventory")).find(x=>sInv&&x.id===sInv.engineId)||{}).laborLogged||0;
await p.click('.rc-ni:has-text("Customers & Jobs")');
await p.click("table.rc-tbl tbody tr:has-text('Engine swap') >> td >> nth=0");
await p.click(".rc-mod button:has-text('+ Log Time')");
await p.locator(".rc-mod select").first().selectOption("Dale");
await p.fill(".rc-mod input[placeholder='Hours']","8");
await p.click(".rc-mod .rc-fa .rc-ba");
await p.waitForSelector("text=Labour profit");
console.log("swap work order:",(await p.locator(".rc-mod .rc-3c").innerText()).replace(/\s+/g," "));
await p.waitForTimeout(900);
const lab1=+((await LS("inventory")).find(x=>sInv&&x.id===sInv.engineId)||{}).laborLogged||0;
console.log("swap hours kept off the engine's cost basis:",lab1===lab0);
// ECM: intake to complete. A "No" emissions answer blocks completion; passed checks at both ends plus the
// customer's sign-off complete it, book the 30/60/90-day follow-ups and bill to an invoice. All of it survives a reload.
await p.click(".rc-ov",{position:{x:5,y:5}}).catch(()=>{});
const ecmTab=l=>p.locator(".rc-mod").getByRole("tab",{name:l,exact:true}).click();
const emis=(sys,when,ans)=>p.click(`.rc-mod button[aria-label="${sys} ${when}: ${ans}"]`);
const ecmJob=async()=>(await LS("ecmJobs")).find(x=>x.unit==="S-1")||{};
await p.click('.rc-ni:has-text("ECM")');
await p.click('button.rc-ba:has-text("+ ECM Job")');
await p.fill(".rc-mod input[placeholder^='Name — add phone']","Smoke ECM Customer");
await p.fill(".rc-mod input[placeholder='Unit #']","S-1");
await p.locator(".rc-mod .rc-fg:has(> label:text-is('Engine family')) select").selectOption("X15");
await p.click(".rc-mod .rc-fa .rc-ba");
await p.waitForSelector(".rc-mod [role=tab]");
await ecmTab("Baseline");
for(const x of ["EGR","DPF","SCR"])await emis(x,"at intake","Yes");
await p.click(".rc-mod button:has-text('+ Fault code')");
await p.locator(".rc-mod input[aria-label='Fault code']").fill("SPN 4364 FMI 18");
await p.locator(".rc-mod input[type=file]").setInputFiles({name:"trip.csv",mimeType:"text/csv",buffer:Buffer.from("rpm,boost_psi\n1500,30\n")});
await p.waitForSelector(".rc-mod >> text=trip.csv");
await ecmTab("Work");
await p.locator(".rc-mod [aria-label='Job type'] button:has-text('Parameter programming')").click();
await p.click(".rc-mod button:has-text('+ Max vehicle speed')");
await p.click(".rc-mod button:has-text('+ Idle shutdown time')");
await p.locator(".rc-mod input[aria-label='New value']").nth(0).fill("105 km/h");
await p.locator(".rc-mod input[aria-label='New value']").nth(1).fill("5 min");
await ecmTab("Verify");
await emis("EGR","at release","Yes");await emis("DPF","at release","No");await emis("SCR","at release","Yes");
await p.fill(".rc-mod .rc-fg:has(> label:text-is('Customer name')) input","Smoke Signer");
await p.locator(".rc-mod input[aria-label='Customer sign-off']").check();
await p.locator(".rc-mod").getByRole("button",{name:"Complete",exact:true}).click();
await p.waitForTimeout(900);
console.log("ECM: release DPF 'No' blocks completion:",(await ecmJob()).status==="on-hold");
await emis("DPF","at release","Yes");
await p.locator(".rc-mod .rc-card button:has-text('Complete job')").click();
await p.waitForTimeout(900);
const ej1=await ecmJob();
console.log("ECM: completed:",ej1.status==="complete","| parameter changes:",(ej1.params||[]).length,"| follow-ups booked:",(await LS("schedule")).filter(a=>+a.ecmJobId===ej1.id).length);
await ecmTab("Work");
await p.locator(".rc-mod .rc-card button:has-text('Bill this job')").click();
await p.waitForSelector(".rc-mod >> text=New Invoice");
await p.click(".rc-mod .rc-fa .rc-ba:has-text('Create')");
await p.waitForTimeout(900);
const ej2=await ecmJob();
console.log("ECM: invoice line exists:",!!ej2.invoiceId&&(await LS("invoices")).some(v=>(v.items||[]).some(l=>l.ecmJobId===ej2.id)));
await p.screenshot({path:"shot-ecm.png"});
await p.reload();
await p.waitForSelector(".rc-side");
const ej3=await ecmJob();
console.log("ECM after reload: status",ej3.status,"| fault codes",(ej3.bFaults||[]).length,"| files",(await LS("ecmFiles")).filter(x=>x.jobId===ej3.id).length,"| parameter changes",(ej3.params||[]).length,"| follow-ups",(await LS("schedule")).filter(a=>+a.ecmJobId===ej3.id).length,"| billed",!!ej3.invoiceId);
// Prospects + competitors: the research seeds load (229 fleets, 292 shops, 14 comparison rows). Log a visit on a
// fleet with a follow-up, convert it to a customer, reload: the stored copy wins and the seed doesn't overwrite it.
// The follow-up shows on the Schedule, and the Brooks route sheet prints on one page.
await p.click('.rc-ni:has-text("Prospects")');
await p.waitForSelector(".rc-pipe");
const fleetsTitle=await p.locator(".rc-sht").first().innerText();
await p.click('.rc-ni:has-text("Competitors")');
const shopsN=await p.locator('.rc-stat:has-text("Shops tracked") .rc-sv').innerText();
await p.click('[role=tab]:has-text("Comparison")');
console.log("research seeds: fleets",(fleetsTitle.match(/\d+/)||[""])[0],"| shops",shopsN,"| comparison rows",await p.locator("table.rc-cmp tbody tr").count());
await p.click('.rc-ni:has-text("Prospects")');
await p.locator(".rc-main table.rc-tbl tbody tr",{hasText:"C & K Trucking Inc"}).locator('button:has-text("Log visit")').click();
await p.waitForSelector(".rc-mod >> text=Log a Visit");
await p.click('.rc-mod button.rc-fb:has-text("Interested")');
await p.fill('.rc-mod textarea[aria-label="Notes"]',"Smoke visit: two ISX15s due this winter.");
await p.check('.rc-mod input[aria-label="Flyer left"]');
await p.click('.rc-mod button.rc-fb:has-text("Today")');
await p.click(".rc-mod .rc-fa .rc-ba");
await p.waitForTimeout(900);
await p.locator(".rc-main table.rc-tbl tbody tr",{hasText:"C & K Trucking Inc"}).locator("td").nth(1).click();
await p.waitForSelector(".rc-mod .rc-pitch");
await p.click('.rc-mod button:has-text("Convert to customer")');
await p.waitForTimeout(900);
await p.click('.rc-mod .rc-fa button:has-text("Close")');
await p.reload();
await p.waitForSelector(".rc-side");
const fleets=await LS("prospects");const ck=fleets.find(r=>r.id==="fleet-001")||{};const ckCust=(await LS("customers")).find(c=>c.prospectId==="fleet-001");
console.log("prospect after reload: fleets",fleets.length,"| visit logged",(ck.log||[]).some(e=>e.type==="visit"&&/Smoke visit/.test(e.notes||"")),"| follow-up",ck.nextFollowUp,"| status",ck.status,"| customer linked both ways",!!ckCust&&ck.customerId===ckCust.id);
await p.click('.rc-ni:has-text("Prospects")');
console.log("seed did not overwrite the edits:",(await p.locator('.rc-pipe-i:has-text("Customer") .n').innerText())==="1"&&(await p.locator('.rc-pipe-i:has-text("Not contacted") .n').innerText())==="228");
await p.click('.rc-ni:has-text("Schedule")');
const fuCard=p.locator(".rc-card",{hasText:"Prospect follow-ups"});
console.log("follow-up on the Schedule:",(await fuCard.count())===1&&(await fuCard.innerText()).includes("C & K Trucking Inc"));
await p.click('.rc-ni:has-text("Prospects")');
await p.click('button:has-text("Route day")');
await p.locator('.rc-mod select[aria-label="Town"]').selectOption("Brooks");
const [route]=await Promise.all([p.waitForEvent("popup"),p.click(".rc-mod .rc-fa .rc-ba")]);
await route.waitForLoadState();
const routePages=((await route.pdf({preferCSSPageSize:true})).toString("latin1").match(/\/Type\s*\/Page(?!s)/g)||[]).length;
console.log("route sheet for Brooks: stops",await route.locator("table.rt tbody").count(),"| pages",routePages);
await route.screenshot({path:"shot-route.png",fullPage:true});
await route.close();
// Shop 3D: the shop loads with every engine placed by status. Giving one a spot moves it, the spot
// survives a reload, and the Engines list shows where it's kept.
await p.click(".rc-ov",{position:{x:5,y:5}}).catch(()=>{});
await p.click('.rc-ni:has-text("Shop 3D")');
await p.waitForSelector(".s3-canvas",{timeout:60000});
await p.waitForFunction(()=>!document.querySelector(".rc-s3-load"),null,{timeout:90000});
const s3Tags=await p.locator(".s3-tag").count();const s3West=await p.locator(".rc-s3-pl",{hasText:"Take-out inventory · West"}).locator("small").innerText();
await p.click('.rc-s3-pl:has-text("Take-out inventory · West")');
const s3Row=p.locator(".rc-s3-erow").first();const s3Sku=(await s3Row.locator("b").innerText()).trim();
await s3Row.click();
await p.locator("#s3-loc").selectOption("reman");
await p.waitForTimeout(900);
await p.screenshot({path:"shot-shop3d.png"});
await p.reload();
await p.waitForSelector(".rc-side");
const s3Eng=(await LS("inventory")).find(x=>x.sku===s3Sku)||{};
await p.click('.rc-ni:has-text("Engines")');
await p.fill(".rc-main input.rc-si",s3Sku);
const s3Loc=(await p.locator(".rc-main table.rc-tbl tbody tr").first().locator(".rc-s3-loc").innerText()).trim();
console.log("shop 3D: place labels",s3Tags,"| take-out West",s3West,"| "+s3Sku+" given a spot:",s3Eng.loc,"| Engines list says",s3Loc);
// Timesheets, localStorage mode. The owner adds Mike and opens his screen, which is exactly what his
// login shows: the whole month, nothing to fill in on days that haven't happened, Full day fills today
// in one tap, an earlier day takes overtime by hand. Approving last month locks it for Mike, the owner
// sees the pay, staff preview hides every dollar, and the pay-period sheet prints on one page.
const shopDay=n=>{const t=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Edmonton",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());const x=new Date(t+"T12:00:00Z");x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10);};
const TODAY=shopDay(0),TOMORROW=shopDay(1);
const PREV=(()=>{const[y,m]=TODAY.split("-").map(Number);return new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7);})();
const PREV_LABEL=new Date(PREV+"-15T12:00:00Z").toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"});
const weekdays=ym=>{const[y,m]=ym.split("-").map(Number),out=[];for(let k=1;k<=31;k++){const x=new Date(Date.UTC(y,m-1,k));if(x.getUTCMonth()!==m-1)break;if(x.getUTCDay()%6)out.push(x.toISOString().slice(0,10));}return out;};
const[PD1,PD2]=weekdays(PREV).slice(1,3);
// Today's day: Full day on a weekday; at the weekend there's no Full day button, so the same times by hand.
const fillToday=async pg=>{if(await pg.locator(".rc-my-today .rc-my-full").count())await pg.click(".rc-my-today .rc-my-full");else{await pg.click('.rc-my-today button:has-text("Other times")');await pg.fill("#ts-start","08:00");await pg.fill("#ts-finish","16:00");await pg.click('.rc-mod .rc-ba:has-text("Save")');}await pg.waitForTimeout(300);};
await p.click(".rc-ov",{position:{x:5,y:5}}).catch(()=>{});
await p.click('.rc-ni:has-text("Team")');
await p.click('button.rc-ba:has-text("+ Employee")');
await p.fill(".rc-mod input[placeholder='Name']","Mike Test");
await p.fill(".rc-mod input[placeholder='Short Name']","Mike");
await p.fill(".rc-mod input[placeholder='Rate ($/hr)']","40");
await p.click(".rc-mod .rc-fa .rc-ba");
await p.click('.rc-ts-seg button:has-text("Timesheets")');
// What Reports shows a login: Payroll/mo, a labour-cost column on the Timesheets table, dollars on Labor by Technician.
const repMoney=async pg=>{const body=await pg.locator(".rc-body").innerText();const th=await pg.locator('.rc-sh:has(.rc-sht:text-is("Timesheets")) + .rc-card thead').innerText().catch(()=>"");const lab=await pg.locator('.rc-sh:has(.rc-sht:text-is("Labor by Technician")) + .rc-card').innerText().catch(()=>"");return "payroll "+/Payroll\/mo/.test(body)+", timesheet labour cost "+/labour cost/i.test(th)+", tech dollars "+/\$\s?\d/.test(lab)+", timesheet tables "+/Unallocated Hours by Week/i.test(body);};
const tsStats=async pg=>(await pg.locator(".rc-stat .rc-sv").allInnerTexts()).join(" / ");
const pickMike=async pg=>{await pg.locator('select[aria-label="Employee"]').selectOption({label:"Mike Test"});};
await pickMike(p);
await p.click('button:has-text("See Mike\'s screen")');
await p.waitForSelector(".rc-emp");
const monthRows=await p.locator(".rc-my-tbl tbody tr:not(.wk)").count(),aheadBtns=await p.locator(".rc-my-tbl tr.fut button").count(),nextShut=await p.locator('button[aria-label="Next month"]').isDisabled();
await fillToday(p);
const todayCard=(await p.locator(".rc-my-today .rc-my-tv").innerText()).replace(/\s+/g," ");
await p.click('button[aria-label="Previous month"]');
await p.locator(`.rc-my-tbl tr[data-date="${PD1}"] button:has-text("Full day")`).click();
await p.locator(`.rc-my-tbl tr[data-date="${PD2}"] button:has-text("Times")`).click();
await p.fill("#ts-start","07:00");await p.fill("#ts-finish","17:30");await p.fill("#ts-notes","Unit 412 injectors");
const live=(await p.locator(".rc-ts-live").innerText()).trim();
await p.click('.rc-mod .rc-ba:has-text("Save")');
await p.waitForTimeout(300);
const prevTot=(await p.locator(".rc-my-month span").innerText()).trim();
await p.screenshot({path:"shot-ts-employee.png",fullPage:true});
console.log("employee screen: rows "+monthRows+" | buttons on days ahead "+aheadBtns+" | next month shut "+nextShut+" | today: "+todayCard+" | editor: "+live+" | "+PREV_LABEL+": "+prevTot);
await p.click('.rc-emp button:has-text("back to the dashboard")');
await p.waitForSelector(".rc-ts-bar");
await pickMike(p);
await p.locator('select[aria-label="Pay period"]').selectOption(PREV+"-01");
const st1=await tsStats(p),appr0=(await p.locator(".rc-ts-appr").innerText()).replace(/\s+/g," ");
await p.click(`button:has-text("Approve ${PREV_LABEL}")`);
await p.waitForTimeout(800);
await p.screenshot({path:"shot-ts-month.png",fullPage:true});
await p.click('button:has-text("See Mike\'s screen")');
await p.click('button[aria-label="Previous month"]');
const lockBtns=await p.locator(`.rc-my-tbl tr[data-date="${PD2}"] button`).count(),lockIcon=await p.locator(`.rc-my-tbl tr[data-date="${PD2}"] .rc-ts-lock`).count();
await p.click('.rc-emp button:has-text("back to the dashboard")');
await p.waitForSelector(".rc-ts-bar");
console.log("owner, "+PREV_LABEL+": "+st1+" | "+appr0+" | approvals "+(await LS("payPeriods")).length+" | Mike's "+PD2+" now: buttons "+lockBtns+", locked "+lockIcon);
await pickMike(p);
await p.locator('select[aria-label="Pay period"]').selectOption(PREV+"-01");
const [tsSheet]=await Promise.all([p.waitForEvent("popup"),p.click('button:has-text("🖨 Print")')]);
await tsSheet.waitForLoadState();
const tsPages=((await tsSheet.pdf({preferCSSPageSize:true})).toString("latin1").match(/\/Type\s*\/Page(?!s)/g)||[]).length;
await tsSheet.screenshot({path:"shot-ts-print.png",fullPage:true});
console.log("pay-period sheet: pages",tsPages,"| gross on it:",(await tsSheet.content()).includes("$790.00"));
await tsSheet.close();
await p.click('button:has-text("Preview as staff")');
const tsStaff=await p.locator(".rc-body").innerText(),staffEd=await p.locator(".rc-ts-tbl .rc-ts-ed").count();
await p.screenshot({path:"shot-ts-staff.png"});
await p.click('.rc-ts-seg button:has-text("Team")');
const teamHead=await p.locator(".rc-main table.rc-tbl thead").first().innerText();
await p.click('.rc-ni:has-text("Reports")');
console.log("staff preview: dollars on Timesheets",/\$\s?\d/.test(tsStaff),"| Gross pay shown",/gross pay/i.test(tsStaff),"| edit buttons",staffEd,"| Team has Rate column",/\bRATE\b/i.test(teamHead),"| Reports: "+await repMoney(p));
await p.click(".rc-ts-prevbar");
const repOwner=await p.locator(".rc-body").innerText();
console.log("owner Reports: "+await repMoney(p)+" | $790.00 for Mike in "+PREV_LABEL,repOwner.includes("$790.00"));
await p.screenshot({path:"shot-ts-reports.png",fullPage:true});
await p.click('.rc-ni:has-text("Team")');
await p.click('.rc-ts-seg button:has-text("Team")');

// Timesheets in the cloud, against the mock Supabase (tests/fixtures/mock-supabase.mjs): a real Postgres
// (PGlite) with the repo's migrations answers every request as the caller's login, so it's the actual
// policies and history trigger at work; the team-logins Edge Function runs bundled. The owner gives Mike
// a login; Mike sees only his timesheet and never asks for other shop data; the database refuses tomorrow
// and an approved day; a changed day keeps its old version; office staff see hours, not dollars.
const SBP=54399,SB="http://127.0.0.1:"+SBP;
const users=[{email:"owner@rollincoal.test",password:"pw-owner-1",app_metadata:{role:"owner"}},{email:"staff@rollincoal.test",password:"pw-staff-1"}];
const fns={};
const sb=await mockSupabase({users,functions:fns});
globalThis.fetch=async(input,init)=>{const u=String(input instanceof Request?input.url:input);return u.startsWith(SB)?sb.handle(input instanceof Request?input:new Request(u,init)):new Response(JSON.stringify({error:"no network in the smoke run"}),{status:503});};
fns["team-logins"]=await loadEdgeFunction("team-logins",{SUPABASE_URL:SB,SUPABASE_ANON_KEY:sb.anonKey,SUPABASE_SERVICE_ROLE_KEY:sb.serviceKey});
await sb.sql("insert into app_state (key, value) values ('rc:employees', $1::jsonb), ('rc:jobs', $2::jsonb), ('rc:timeEntries', $3::jsonb)",[JSON.stringify([{id:101,name:"Mike Test",nick:"Mike",role:"Diesel Tech",rate:40,hrs:40,status:"active"}]),JSON.stringify([{id:301,kind:"service",vehicle:"Unit 412 · 2016 Kenworth T880",service:"Injector job",tech:"Mike",status:"in-progress",custId:0}]),JSON.stringify([{id:401,jobId:301,tech:"Mike",date:PD2,hours:6,rate:40}])]);
const mockSrv=createServer(async(req,res)=>{const chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks);const rq=new Request(SB+req.url,{method:req.method,headers:Object.fromEntries(Object.entries(req.headers).filter(([k])=>k!=="host"&&k!=="connection"&&k!=="content-length")),body:["GET","HEAD"].includes(req.method)?undefined:body});
  const r=await sb.handle(rq);const h=Object.fromEntries(r.headers);h["access-control-allow-origin"]="*";res.writeHead(r.status,h);res.end(Buffer.from(await r.arrayBuffer()));}).listen(SBP,"127.0.0.1");
execSync("npx vite build --outDir dist-smoke-cloud --emptyOutDir",{stdio:"ignore",env:{...process.env,VITE_SUPABASE_URL:SB,VITE_SUPABASE_ANON_KEY:sb.anonKey}});
const srv2=spawn("npx",["vite","preview","--port","4174","--strictPort","--outDir","dist-smoke-cloud"],{stdio:"ignore"});
await new Promise(r=>setTimeout(r,2500));
const cx=await b.newContext({viewport:{width:1280,height:900}});const q=await cx.newPage();
q.on("pageerror",e=>errs.push("cloud pageerror: "+e.message));
q.on("console",m=>{if(m.type()==="error")errs.push("cloud console: "+errOf(m));});
const signIn=async(email,pw,ready=".rc-side")=>{await q.waitForSelector("input[type=email]");await q.fill("input[type=email]",email);await q.fill("input[type=password]",pw);await q.click("button[type=submit]");await q.waitForSelector(ready);};
const signOut=async()=>{await q.click('.rc-link:has-text("Sign out")');await q.waitForSelector("input[type=email]");};
const toTimesheets=async()=>{await q.click('.rc-ni:has-text("Team")');await q.click('.rc-ts-seg button:has-text("Timesheets")');await q.waitForSelector(".rc-ts-bar");await pickMike(q);await q.locator('select[aria-label="Pay period"]').selectOption(PREV+"-01");};
const dbDay=async date=>((await sb.sql("select data from timesheet_entries where employee_id = 101 and work_date = $1::date",[date]))[0]||{}).data||null;
const MIKE="mike@rollincoal.test";
await q.goto("http://localhost:4174/");
await signIn(users[0].email,users[0].password);
await q.click('.rc-ni:has-text("Team")');
await q.click('button:has-text("Give a login")');
await q.fill("#lg-email",MIKE);
await q.waitForFunction(()=>(document.querySelector("#lg-pass")||{}).value?.length>=8);   // the form fills in a temporary password one render after it opens
let mikePw=await q.inputValue("#lg-pass");
await q.click('.rc-mod button:has-text("Create login")');
await q.waitForSelector(".rc-ts-okbox");
const cred=(await q.locator(".rc-ts-cred").innerText()).replace(/\s+/g," "),cardPw=(await q.locator(".rc-ts-cred div:has(span:text-is('Password')) b").innerText()).trim();
const mikeU=sb.users.find(u=>u.email===MIKE)||{};
console.log("owner gave Mike a login: "+JSON.stringify(mikeU.app_metadata)+" | card shows the password "+(cardPw===mikePw)+" ("+mikePw.replace(/\d/g,"#")+")"+" | Team shows "+JSON.stringify(await (async()=>{await q.click('.rc-mod button:has-text("Close")');return (await q.locator(".rc-main table.rc-tbl tbody tr:has-text('Mike Test')").innerText()).match(/Timesheet login|Give a login/)?.[0];})()));
await signOut();
let mark=sb.log.length;
await signIn(MIKE,mikePw,".rc-emp");
const mikeNav=await q.locator(".rc-side").count();
await fillToday(q);
await q.click('button[aria-label="Previous month"]');
await q.locator(`.rc-my-tbl tr[data-date="${PD2}"] button:has-text("Times")`).click();
await q.fill("#ts-start","07:00");await q.fill("#ts-finish","17:30");await q.fill("#ts-notes","Unit 412 injectors");
await q.click('.rc-mod .rc-ba:has-text("Save")');
await q.waitForTimeout(1500);
await q.locator(`.rc-my-tbl tr[data-date="${PD2}"] button:has-text("Edit")`).click();
await q.fill("#ts-finish","17:00");
await q.click('.rc-mod .rc-ba:has-text("Save")');
await q.waitForTimeout(1500);
const tRow=await dbDay(TODAY),pRow=await dbDay(PD2);
const mikeAsked=sb.log.slice(mark).filter(e=>e.email===MIKE&&/\/rest\/v1\/(app_state|inventory)|\/storage\/v1\//.test(e.path)).length;
await q.click('.rc-emp-who button:has-text("Password")');
await q.fill("#pw1","Torque-2026-Cam");await q.fill("#pw2","Torque-2026-Cam");
await q.click('.rc-mod .rc-ba:has-text("Save")');
await q.waitForSelector('.rc-toast:has-text("Password changed")');
mikePw="Torque-2026-Cam";
console.log("Mike's login: sidebar "+mikeNav+" | asked for other shop data "+mikeAsked+" | today in the database "+(tRow&&tRow.start+" to "+tRow.finish+" by "+tRow.by)+" | "+PD2+" "+(pRow&&pRow.start+" to "+pRow.finish)+", history "+JSON.stringify((pRow&&pRow.history||[]).map(h=>h.finish)));
const mikeTok=sb.session(sb.users.find(u=>u.email===MIKE)).access_token;
const api=(method,path,body)=>sb.handle(new Request(SB+path,{method,headers:{apikey:sb.anonKey,Authorization:"Bearer "+mikeTok,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"},body:body&&JSON.stringify(body)}));
const ahead=await api("POST","/rest/v1/timesheet_entries",[{id:"101|"+TOMORROW,employee_id:101,work_date:TOMORROW,data:{start:"8:00 AM",finish:"4:00 PM"}}]);
const shopData=await (await api("GET","/rest/v1/app_state?select=key")).json();
console.log("Mike straight at the database: tomorrow "+ahead.status+" | app_state rows "+shopData.length);
await signOut();
await signIn(users[0].email,users[0].password);
await toTimesheets();
const cs=await tsStats(q);
await q.locator(`.rc-ts-tbl tr[data-date="${PD2}"] button:has-text("edited")`).click();
const hist=(await q.locator(".rc-ts-tbl tr.why").innerText()).replace(/\s+/g," ");
await q.click(`button:has-text("Approve ${PREV_LABEL}")`);
await q.waitForTimeout(1500);
const apprN=(await sb.sql("select count(*)::int as n from timesheet_approvals"))[0].n;
await q.screenshot({path:"shot-ts-cloud.png",fullPage:true});
console.log("owner, cloud: "+cs+" | history: "+hist+" | approvals in the database "+apprN);
const locked=await api("POST","/rest/v1/timesheet_entries",[{id:"101|"+PD2,employee_id:101,work_date:PD2,data:{start:"7:00 AM",finish:"11:00 PM"}}]);
const pAfter=await dbDay(PD2);
await signOut();
await signIn(MIKE,mikePw,".rc-emp");
await q.click('button[aria-label="Previous month"]');
const mikeLock=await q.locator(`.rc-my-tbl tr[data-date="${PD2}"] .rc-ts-lock`).count(),mikeLockBtns=await q.locator(`.rc-my-tbl tr[data-date="${PD2}"] button`).count();
console.log("approved day: Mike's API change "+locked.status+", still "+(pAfter&&pAfter.finish)+" | his screen: locked "+mikeLock+", buttons "+mikeLockBtns+" | new password worked true");
await signOut();
await signIn(users[1].email,users[1].password);
await toTimesheets();
const staffTs=await q.locator(".rc-body").innerText(),staffEdit=await q.locator(".rc-ts-tbl .rc-ts-ed").count();
await q.screenshot({path:"shot-ts-cloud-staff.png",fullPage:true});
await q.click('.rc-ts-seg button:has-text("Team")');const staffHead=await q.locator(".rc-main table.rc-tbl thead").first().innerText();
await q.click('.rc-ni:has-text("Reports")');const staffRep=await repMoney(q);
console.log("staff login: dollars on Timesheets",/\$\s?\d/.test(staffTs),"| sees the hours",staffTs.includes("10.00"),"| edit buttons",staffEdit,"| Rate column",/\bRATE\b/i.test(staffHead),"| Login column",/\bLOGIN\b/i.test(staffHead),"| Reports: "+staffRep);
await cx.close();srv2.kill();mockSrv.close();
console.log("errors:",errs.length?errs:"none");
await b.close();srv.kill();process.exit(0);
