// ─────────────────────────────────────────────────────────────
// Common-issues starter set — well-known failure modes for the engine
// families Rollin Coal carries. Every row is editable/deletable in the
// Issues tab; source:"seed" marks it as a starter, source:"shop" marks
// findings promoted from a real diagnosis on the floor.
//
// models: match tokens (see FAMILIES in the dashboard) — an engine matches
//         when its normalized name contains one of these. [] = every engine.
// symptoms: tags from SYMPTOMS in the dashboard (free text allowed too).
// severity: high | medium | low
// ─────────────────────────────────────────────────────────────
export const ISSUE_SEED=[
// ── Cummins ──
{id:70001,source:"seed",severity:"high",models:["ISX15"],title:"XPI high-pressure fuel pump failure (CM2250, 2010–13)",symptoms:["Hard start","No start","Low power","Derate / fault codes"],
 causes:"XPI pump internal wear sheds metal into the rail, lines and injectors. Common on 2010–2013 ISX15 CM2250; many trucks got the updated pump under campaign.",
 confirm:"Cut open the fuel filter and look for metal flake. Check rail pressure vs commanded (SPN 157 codes). Inspect the pump outlet fittings for debris.",
 fix:"Replace the XPI pump. If metal is found, replace all six injectors and flush/replace rails, lines and fuel filter housing — debris will kill new injectors.",
 parts:"XPI pump, injectors (6), fuel filters, rail/line set",notes:""},
{id:70002,source:"seed",severity:"high",models:["ISX"],title:"Camshaft / rocker & follower wear (dual-cam CM870/CM871, 2002–09)",symptoms:["Knock / noise","Low power","Misfire","Excessive blowby"],
 causes:"Injector cam lobes and rocker rollers spall — often from extended oil drains or wrong oil. Once one lobe goes, the metal takes out others.",
 confirm:"Pull the valve cover. Inspect every injector cam lobe and rocker roller for pitting/flaking. Check overhead lash; look for metal in the oil filter.",
 fix:"Replace camshaft(s), rockers and followers as a set. Flush oil galleries; new oil cooler if metal is present.",
 parts:"Injector cam, rockers/followers, gaskets, oil cooler",notes:"Budget for this on any pre-2010 ISX core before pricing the build."},
{id:70003,source:"seed",severity:"medium",models:["ISX"],title:"EGR cooler internal leak",symptoms:["Coolant loss","White smoke","Overheating"],
 causes:"Cooler core cracks from thermal cycling; coolant is pushed into the intake and burned.",
 confirm:"Coolant drops with no external leak. Pressure-test the cooler off the engine; white sweet-smelling smoke at start-up; coolant residue in the EGR crossover/intake.",
 fix:"Replace EGR cooler; inspect EGR valve and intake for coolant residue. Verify head gasket isn't the real culprit first.",
 parts:"EGR cooler, gaskets, coolant",notes:""},
{id:70004,source:"seed",severity:"medium",models:["ISX"],title:"Injector cup (sleeve) leak — coolant in fuel / fuel in coolant",symptoms:["Hard start","Coolant loss","Overheating","Rough idle"],
 causes:"Copper injector cups crack or lose their seal, letting coolant into the fuel system or fuel into the coolant.",
 confirm:"Fuel smell or sheen in the coolant tank; coolant in the fuel filter; pressure-test the cooling system with the injectors out.",
 fix:"Re-cup the affected cylinders (or all six on a reman). Replace injectors that ingested coolant.",
 parts:"Injector cups/sleeves, cup sealant, injector seals",notes:""},
{id:70005,source:"seed",severity:"high",models:["ISX"],title:"Liner cavitation / coolant in oil",symptoms:["Coolant in oil","Coolant loss"],
 causes:"Neglected coolant additive (SCA/OAT) lets cavitation pit through the wet liners.",
 confirm:"Milky oil, oil analysis shows glycol/sodium. Pull liners and look for pitting on the thrust side.",
 fix:"Liners, pistons/rings as needed, full oil-system flush. Set up coolant properly on delivery and put it on the customer's break-in sheet.",
 parts:"Liner kit, liner seals, oil cooler, coolant",notes:""},
{id:70006,source:"seed",severity:"medium",models:["ISB"],title:"VGT turbo / actuator sticking (6.7 ISB, 2007.5+)",symptoms:["Low power","Derate / fault codes","Turbo / boost"],
 causes:"Soot builds up in the variable-geometry sliding nozzle; actuator can't move it. Actuator electronics also fail from heat.",
 confirm:"Actuator calibration/range test with the tool; boost low vs commanded; codes for turbo actuator position.",
 fix:"Clean or replace the VGT cartridge and calibrate the actuator; replace the actuator if calibration fails.",
 parts:"VGT turbo/cartridge, actuator",notes:""},
{id:70007,source:"seed",severity:"medium",models:["ISB","ISL","PX8","PX6"],title:"Leaking injectors — fuel dilution of engine oil",symptoms:["Fuel in oil","Rough idle","Misfire","Oil consumption"],
 causes:"Cracked injector bodies or worn seals return fuel into the crankcase. Common on high-hour ISB/ISL/PX.",
 confirm:"Oil level rising, diesel smell in oil, oil analysis fuel %. Injector return-flow (leak-back) test isolates the cylinder.",
 fix:"Replace the leaking injector(s) and seals; change oil and filter. On a reman, replace as a set.",
 parts:"Injectors, injector seal kit, oil/filter",notes:""},
{id:70008,source:"seed",severity:"medium",models:["ISL","PX8"],title:"EGR cooler failure (ISL / Paccar PX-8)",symptoms:["Coolant loss","White smoke","Overheating"],
 causes:"Same failure mode as the ISX: cooler core cracks and coolant is drawn into the intake.",
 confirm:"Coolant loss with no external leak; pressure-test cooler; check intake for coolant residue.",
 fix:"Replace the cooler and clean the EGR valve/intake. Check for a plugged cooler on the way out as it'll also cause overheating.",
 parts:"EGR cooler, gaskets",notes:""},
{id:70009,source:"seed",severity:"medium",models:["N14"],title:"Injector harness chafe & cam follower wear (N14 Celect / Celect Plus)",symptoms:["Misfire","Rough idle","Derate / fault codes","Knock / noise"],
 causes:"The under-valve-cover harness and pass-through connector chafe and short; separately, cam followers wear and take the lobes with them.",
 confirm:"Wiggle-test the injector harness with the engine running; check pass-through connector pins. Pull covers and inspect followers/cam lobes.",
 fix:"Replace the internal injector harness and pass-through; replace worn followers and cam.",
 parts:"Injector harness, pass-through connector, cam followers, camshaft",notes:""},
// ── Detroit ──
{id:70010,source:"seed",severity:"medium",models:["DD13","DD15"],title:"EGR cooler leak (DD13 / DD15)",symptoms:["Coolant loss","White smoke","Coolant in oil"],
 causes:"Cooler cracks internally; coolant goes into the intake or, less often, the crankcase.",
 confirm:"Coolant loss with no external leak; pressure test; borescope the intake for coolant residue; white smoke on start.",
 fix:"Replace the EGR cooler; clean the EGR valve and check the delta-P sensor and lines.",
 parts:"EGR cooler, gaskets, delta-P sensor",notes:""},
{id:70011,source:"seed",severity:"high",models:["DD13","DD15","DD16"],title:"High-pressure fuel pump failure — metal in fuel system (Bosch pump, ~2011–16)",symptoms:["Hard start","No start","Low power","Derate / fault codes"],
 causes:"Bosch high-pressure pump internal failure sends metal downstream. Detroit had a campaign for the updated pump.",
 confirm:"Cut the fuel filter, check for metal. Rail pressure low vs commanded. Inspect pump outlet and rail fittings.",
 fix:"Replace pump with the updated part; if contaminated, replace injectors and flush/replace rails and lines.",
 parts:"HP fuel pump, injectors, rails/lines, filters",notes:"Same logic as the ISX XPI — never put new injectors on a dirty rail."},
{id:70012,source:"seed",severity:"medium",models:["DD15"],title:"Turbo-compound axial power turbine bearing / oil leak",symptoms:["Oil consumption","Blue smoke","Knock / noise"],
 causes:"The turbo-compound power turbine's bearings and seals wear; oil leaks into the exhaust or the gear train gets noisy.",
 confirm:"Oil in exhaust after the turbo; inspect the power turbine and its gearbox; check for play/noise.",
 fix:"Replace the power turbine / gearbox assembly; inspect the turbine coupling.",
 parts:"Axial power turbine, coupling, seals",notes:""},
{id:70013,source:"seed",severity:"medium",models:["DD13","DD15"],title:"Injector cup leak — coolant into cylinder",symptoms:["White smoke","Coolant loss","Hard start"],
 causes:"Injector cups/sleeves lose their seal and let coolant into the combustion chamber.",
 confirm:"White smoke and coolant loss; pressure-test the cooling system with injectors out and watch for weeping cups.",
 fix:"Replace injector cups and seals on affected cylinders; replace injector if damaged.",
 parts:"Injector cups, seals, injectors",notes:""},
{id:70014,source:"seed",severity:"low",models:["DD13","DD15"],title:"Aftertreatment faults — DPF soot load / DEF doser / NOx sensors",symptoms:["Derate / fault codes","EGR / aftertreatment","Low power"],
 causes:"High soot load, failed DEF doser or NOx sensors force derates. Often a symptom of something upstream (EGR, injectors, turbo).",
 confirm:"Read soot load and regen history; test DEF doser spray; check NOx sensor readings vs each other.",
 fix:"Fix the upstream cause first; then clean/replace DPF, doser, sensors; forced regen.",
 parts:"DEF doser, NOx sensors, DPF clean/exchange",notes:"Buyers of a reman with the aftertreatment stripped need to know this comes with the truck, not the engine."},
{id:70015,source:"seed",severity:"high",models:["60SERIES"],title:"Cylinder head cracking / injector harness (Series 60 12.7 & 14L)",symptoms:["Coolant loss","White smoke","Misfire","Coolant in oil"],
 causes:"Heads crack between valves (14L especially) and leak coolant; the internal injector harness chafes and shorts.",
 confirm:"Pressure-test the head; check for coolant in cylinders; wiggle-test the injector harness under the valve cover.",
 fix:"Replace/repair head; new head gasket; new injector harness on any Series 60 reman.",
 parts:"Cylinder head, head gasket, injector harness",notes:""},
{id:70016,source:"seed",severity:"medium",models:["60SERIES"],title:"EGR valve / cooler (DDEC V & VI, 2002+)",symptoms:["Coolant loss","Low power","Derate / fault codes"],
 causes:"EGR valve sticks with soot; cooler leaks coolant into the intake.",
 confirm:"EGR valve position vs commanded; pressure-test the cooler; coolant residue in intake.",
 fix:"Clean/replace the EGR valve; replace the cooler.",
 parts:"EGR valve, EGR cooler",notes:""},
// ── Caterpillar ──
{id:70017,source:"seed",severity:"high",models:["3126","C7"],title:"HEUI high-pressure oil system — low IAP / hard start",symptoms:["Hard start","No start","Low power","Rough idle"],
 causes:"Injection actuation pressure can't build: worn HEUI pump, sticking IAP control valve, leaking injector o-rings, or low oil level/wrong oil.",
 confirm:"Compare actual vs desired IAP with the tool while cranking; check for oil leaks at injector o-rings (oil in the fuel), pump output.",
 fix:"Replace the HEUI pump and IAPCV as needed; new injector o-rings; correct oil spec.",
 parts:"HEUI pump, IAP control valve, injector o-ring kit",notes:"Cranking with a healthy battery matters — HEUI needs oil pressure before it will fire."},
{id:70018,source:"seed",severity:"medium",models:["3116","3126","C7"],title:"Cylinder head cracking between valves",symptoms:["Coolant loss","White smoke","Coolant in oil","Overheating"],
 causes:"Heads crack between the valve seats after overheating events; coolant enters the cylinder.",
 confirm:"Pressure-test the head; coolant in cylinders; look for steam-cleaned pistons.",
 fix:"Replace/repair the head, head gasket; find and fix the overheating cause.",
 parts:"Cylinder head, head gasket",notes:""},
{id:70019,source:"seed",severity:"medium",models:["C7"],title:"Injector failure — fuel in oil / dead cylinder (C7 ACERT)",symptoms:["Fuel in oil","Misfire","Rough idle","Black smoke"],
 causes:"Injector tips and internal seals fail; fuel dilutes the oil or a cylinder drops out.",
 confirm:"Cylinder cutout test; oil level rising / fuel smell; injector solenoid codes.",
 fix:"Replace failed injector(s) with seals; change oil and filter.",
 parts:"Injectors, seal kit",notes:""},
{id:70020,source:"seed",severity:"medium",models:["C15","C13"],title:"ACERT twin-turbo & valve-bridge issues (C15 2004–07)",symptoms:["Low power","Turbo / boost","Knock / noise","Oil consumption"],
 causes:"Series turbos wear/leak oil; valve bridges and adjusters wear and let lash drift.",
 confirm:"Check turbo shaft play and oil in the intake; inspect valve bridges and lash on overhead.",
 fix:"Replace turbos; replace bridges/adjusters and reset overhead.",
 parts:"Turbochargers, valve bridges, overhead gaskets",notes:"C15 is scarce — hold margin and say so on the listing."},
{id:70021,source:"seed",severity:"medium",models:["C15","3406"],title:"Oil cooler leak — coolant in oil (C15 / 3406E)",symptoms:["Coolant in oil","Coolant loss"],
 causes:"Oil cooler core corrodes/cracks and coolant contaminates the oil.",
 confirm:"Milky oil / oil analysis; pressure-test the oil cooler off the engine.",
 fix:"Replace oil cooler; flush the oil system; check bearings if it ran long on contaminated oil.",
 parts:"Oil cooler, gaskets, oil/filter",notes:""},
// ── International / Navistar ──
{id:70022,source:"seed",severity:"high",models:["DT466","T444E","MAXXFORCEDT"],title:"HEUI: ICP sensor / IPR valve / high-pressure oil pump",symptoms:["Hard start","No start","Low power","Rough idle"],
 causes:"Same HEUI logic as Cat: the high-pressure oil side can't hold pressure — ICP sensor lies, IPR valve sticks, pump or reservoir check valve leaks down.",
 confirm:"ICP actual vs desired while cranking (needs ~500 psi to fire); IPR duty cycle pegged; check for aerated oil.",
 fix:"Replace ICP sensor/IPR first (cheap); then pump; fix any oil leak into the high-pressure rail (o-rings, stand pipes).",
 parts:"ICP sensor, IPR valve, HP oil pump, rail o-rings",notes:""},
{id:70023,source:"seed",severity:"medium",models:["DT466","T444E"],title:"Injector o-rings — fuel in oil / oil in fuel",symptoms:["Fuel in oil","Rough idle","Hard start","Oil consumption"],
 causes:"Injector o-rings harden and leak between the fuel and high-pressure oil galleries.",
 confirm:"Oil level rising / fuel smell; oil in the fuel filter; leak-down of ICP with engine off.",
 fix:"Reseal injectors with a new o-ring kit; change oil.",
 parts:"Injector o-ring kits, oil/filter",notes:""},
{id:70024,source:"seed",severity:"medium",models:["T444E"],title:"UVC (under valve cover) harness / glow plug circuit",symptoms:["Misfire","Hard start","Rough idle"],
 causes:"The under-valve-cover harness insulation breaks down; injectors or glow plugs drop out.",
 confirm:"Dead-cylinder test; resistance check injector and glow plug circuits through the UVC connector.",
 fix:"Replace the UVC harness; glow plugs/relay as needed.",
 parts:"UVC harness, glow plugs, relay",notes:""},
{id:70025,source:"seed",severity:"medium",models:["DT466","MAXXFORCEDT"],title:"EGR valve / cooler (2004+ DT466E & MaxxForce DT)",symptoms:["Coolant loss","Low power","Derate / fault codes","White smoke"],
 causes:"EGR valve sticks with carbon; cooler cracks and leaks coolant into the intake.",
 confirm:"EGR valve position vs commanded; pressure-test the cooler; coolant residue in intake.",
 fix:"Clean/replace EGR valve; replace cooler.",
 parts:"EGR valve, EGR cooler",notes:""},
{id:70026,source:"seed",severity:"high",models:["MAXXFORCE13","MAXXFORCE11"],title:"EGR cooler, cracked heads & turbo failures (MaxxForce 13)",symptoms:["Coolant loss","White smoke","Low power","Derate / fault codes","Turbo / boost"],
 causes:"Heavy EGR strategy overworks the coolers and heads; twin turbos and injectors fail early. Widely documented across the 2008–2013 EGR-only engines.",
 confirm:"Pressure-test coolers and head; check both turbos for play/oil; cylinder cutout for injectors.",
 fix:"Coolers, head repair/replace, turbos, injectors as found. Price the core low — these get expensive.",
 parts:"EGR coolers, cylinder head, turbos, injectors",notes:"Be honest on the listing about the reputation; buyers know."},
{id:70027,source:"seed",severity:"medium",models:["MAXXFORCEDT"],title:"Fuel dilution & cracked heads (MaxxForce DT)",symptoms:["Fuel in oil","Coolant loss","White smoke"],
 causes:"Injector seals leak fuel into the oil; heads crack from EGR heat.",
 confirm:"Oil analysis for fuel; pressure-test the head.",
 fix:"Injectors/seals; head repair or replace.",
 parts:"Injectors, head, head gasket",notes:""},
// ── Mack / Volvo ──
{id:70028,source:"seed",severity:"medium",models:["MP7","MP8","VOLVOD11","VOLVOD13"],title:"EGR cooler, VGT actuator & DPF faults (MP7/MP8, D11/D13)",symptoms:["Low power","Derate / fault codes","Coolant loss","Turbo / boost"],
 causes:"EGR cooler cracks; VGT actuator/turbo sticks; aftertreatment fights back with derates.",
 confirm:"Pressure-test cooler; turbo actuator range test; soot load.",
 fix:"Cooler, actuator/turbo cartridge, clean DPF.",
 parts:"EGR cooler, VGT actuator, turbo",notes:""},
{id:70029,source:"seed",severity:"medium",models:["VED12"],title:"Cylinder head cracking & injector cup leaks (Volvo D12 / VED12)",symptoms:["Coolant loss","White smoke","Hard start"],
 causes:"Heads crack; injector cups (copper sleeves) leak coolant into the cylinders.",
 confirm:"Pressure-test the head with injectors out; watch cups for weeping.",
 fix:"Re-cup; repair/replace the head.",
 parts:"Injector cups, cylinder head, head gasket",notes:""},
// ── Mercedes ──
{id:70030,source:"seed",severity:"medium",models:["OM9"],title:"Unit-pump o-rings — fuel in oil (MBE900 OM906/OM926)",symptoms:["Fuel in oil","Rough idle","Hard start"],
 causes:"The unit pump o-rings leak fuel into the crankcase; also the EGR valve sticks on later engines.",
 confirm:"Oil level rising / fuel smell; pull unit pumps and inspect o-rings; EGR valve position test.",
 fix:"Reseal unit pumps; EGR valve clean/replace.",
 parts:"Unit pump o-ring kits, EGR valve",notes:""},
// ── Ford ──
{id:70031,source:"seed",severity:"high",models:["FORD67"],title:"CP4 high-pressure fuel pump failure (6.7 Power Stroke 2011–19)",symptoms:["No start","Hard start","Low power","Derate / fault codes"],
 causes:"The Bosch CP4.2 pump self-destructs and sends metal through the entire fuel system. P0087 low rail pressure is the classic code.",
 confirm:"Metal in the fuel filter housing; low rail pressure; pump roller/cam damage on teardown.",
 fix:"Full fuel system: pump, injectors, rails, lines, filters, clean tank. No shortcuts.",
 parts:"CP4 pump (or CP3 conversion), injectors (8), rails, lines, filters",notes:""},
{id:70032,source:"seed",severity:"medium",models:["FORD67"],title:"Early turbo ceramic bearing & EGT sensor faults (6.7 Power Stroke 2011–12)",symptoms:["Turbo / boost","Low power","Derate / fault codes","Knock / noise"],
 causes:"2011–12 turbos with ceramic ball bearings fail; EGT sensors drift and trigger derates.",
 confirm:"Turbo shaft play/noise; EGT sensor readings vs each other cold.",
 fix:"Updated turbo; EGT sensor(s).",
 parts:"Turbocharger, EGT sensors",notes:""},
// ── GM ──
{id:70033,source:"seed",severity:"medium",models:["GM65"],title:"PMD / FSD driver failure on the DS4 injection pump (GM 6.5)",symptoms:["No start","Hard start","Derate / fault codes","Rough idle"],
 causes:"The pump-mounted driver overheats and dies — stalls when hot, restarts once cooled. Also watch for cracked block webbing and failed harmonic balancers.",
 confirm:"Stall-when-hot pattern; swap in a known-good PMD; check block main webs for cracks on a teardown.",
 fix:"Replace the PMD and relocate it with a heat-sink kit away from the pump.",
 parts:"PMD/FSD, relocation kit, harmonic balancer",notes:""},
// ── Small / auxiliary ──
{id:70034,source:"seed",severity:"medium",models:["YANMAR"],title:"Overheating & head gasket (Yanmar TK reefer engines)",symptoms:["Overheating","Coolant loss","White smoke"],
 causes:"Cooling systems get neglected in reefer units; heads warp and gaskets fail.",
 confirm:"Pressure-test; check head for warp; inspect water pump and radiator.",
 fix:"Head gasket, surface the head, water pump/thermostat.",
 parts:"Head gasket, water pump, thermostat",notes:""},
{id:70035,source:"seed",severity:"medium",models:["DEUTZ"],title:"Air-cooled overheating — fan drive / belt / dirty fins (Deutz)",symptoms:["Overheating","Low power","Knock / noise"],
 causes:"No coolant to lose: a slipping fan belt or blocked cooling fins cooks the cylinders and heads.",
 confirm:"Check fan belt tension/condition, fin cleanliness, oil cooler airflow; look for scored cylinders.",
 fix:"Belt, fan bearing, clean fins; cylinder/head replacement if scored.",
 parts:"Fan belt, fan bearing, cylinder kit",notes:""},
// ── Universal triage ──
{id:70036,source:"seed",severity:"medium",models:[],title:"Coolant loss with no external leak — triage order",symptoms:["Coolant loss","White smoke","Coolant in oil","Overheating"],
 causes:"Somewhere it's leaving internally: EGR cooler, oil cooler, injector cups, head gasket, cracked head, or liner cavitation.",
 confirm:"1) Pressure-test the system cold and hot. 2) Check the oil for glycol. 3) Check the intake/EGR for residue. 4) Cylinders: pull injectors and look for a washed piston. 5) Then head/liners.",
 fix:"Fix what the test points to — don't throw a head gasket at an EGR cooler.",
 parts:"",notes:"Cheapest tests first."},
{id:70037,source:"seed",severity:"medium",models:[],title:"Fuel in oil — triage order",symptoms:["Fuel in oil","Oil consumption","Rough idle"],
 causes:"Injector seals/o-rings, cracked injector body, unit pump seals (MBE), lift/transfer pump diaphragm, or HEUI oil-side leaks masquerading as fuel.",
 confirm:"Confirm with oil analysis (fuel %). Injector leak-back test to isolate a cylinder. Check lift pump for diaphragm failure on mechanical engines.",
 fix:"Reseal or replace the offending injector/pump; oil change; retest after 500 km.",
 parts:"",notes:""},
];
